package projecteuler;

import java.util.HashSet;

public class Problem029 {

	/**
	 * Calculates the number of distinct terms in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100
	 */
	static void solution() {
		HashSet<Double> S = new HashSet<Double>();
		for (int a = 2; a <= 100; a++)
			for (int b = 2; b <= 100; b++)
				S.add(Math.pow(a, b));
		System.out.println(S.size());
	}
}